"""empty message

Revision ID: ebed79f18aea
Revises: 
Create Date: 2022-07-08 15:12:40.318743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebed79f18aea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BookCopies',
    sa.Column('BookID', sa.Integer(), nullable=False),
    sa.Column('ISBN', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('BookID')
    )
    op.create_table('BookModel',
    sa.Column('ISBN', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ISBN')
    )
    op.create_table('BorrowedBooks',
    sa.Column('BookID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('DueDate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('BookID')
    )
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('UserID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    op.drop_table('BorrowedBooks')
    op.drop_table('BookModel')
    op.drop_table('BookCopies')
    # ### end Alembic commands ###
